/* extern const byte* ff1_open[];
 * -- generated by midi_converter from file ff1_open.mid
 */

#define D(x) x                     /* wait x frames */
#define X(c) 127+(c)               /* channel c off */
#define N(c,n) 143+(c),(n)         /* channel c on, note=n */
#define M(c,n,v) 159+(c),(n),(v)   /* channel c on, note=n, wavA=v */
#define byte unsigned char
#define nohop __attribute__((nohop))

nohop const byte *ff1_open[] = {
,
  0
};
